import type {
  Request,
  Response,
  NextFunction,
} from "express";

import {
  cloudflareRealtimeProvider,
} from "../../lib/media/cloudflare/cloudflare-realtime";

/**
 * GET /api/v1/media/test/config
 *
 * Returns Cloudflare Realtime configuration status.
 */
export async function testCloudflareConfig(
  _req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    res.json({
      status: "ok",

      data: {
        provider:
          "cloudflare-realtime",

        configured:
          cloudflareRealtimeProvider.isConfigured(),

        configuration:
          cloudflareRealtimeProvider.getConfiguration(),
      },
    });
  } catch (error) {
    next(error);
  }
}

/**
 * POST /api/v1/media/test/session
 *
 * Creates a Cloudflare media session
 * using the SDP offer generated by the browser.
 *
 * Body:
 *
 * {
 *   "roomId": "phase1-test-room",
 *   "offerSdp": "v=0..."
 * }
 */
export async function testCreateSession(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const userId =
      (req as any).user?.id ??
      "phase1-test-user";

    const roomId =
      String(
        req.body?.roomId ??
          "phase1-test-room",
      ).trim();

    const offerSdp =
      typeof req.body?.offerSdp ===
      "string"
        ? req.body.offerSdp
        : "";

    /*
     * Validate room.
     */
    if (!roomId) {
      res.status(400).json({
        status: "error",

        error: {
          code:
            "MEDIA_ROOM_ID_REQUIRED",

          message:
            "roomId is required.",
        },
      });

      return;
    }

    /*
     * Validate browser-generated SDP.
     */
    if (!offerSdp.trim()) {
      res.status(400).json({
        status: "error",

        error: {
          code:
            "MEDIA_SDP_OFFER_REQUIRED",

          message:
            "offerSdp is required. Generate it from a browser RTCPeerConnection before creating the Cloudflare media session.",
        },
      });

      return;
    }

    /*
     * Temporary diagnostic logging for Phase 1.
     *
     * Do NOT log the entire SDP because it contains
     * WebRTC negotiation information.
     */
    console.log(
      "[media-test] Creating session",
      {
        roomId,

        userId,

        offerSdpLength:
          offerSdp.length,

        offerSdpEnding:
          JSON.stringify(
            offerSdp.slice(-100),
          ),
      },
    );

    const result =
      await cloudflareRealtimeProvider.createSession({
        roomId,

        userId,

        role: "viewer",

        generation: 1,

        offerSdp,
      });

    res.status(201).json({
      status: "ok",

      data: {
        sessionId:
          result.session.sessionId,

        roomId:
          result.session.roomId,

        userId:
          result.session.userId,

        role:
          result.session.role,

        generation:
          result.session.generation,

        status:
          result.session.status,

        sessionDescription:
          result.sessionDescription,
      },
    });
  } catch (error) {
    next(error);
  }
}

/**
 * POST /api/v1/media/test/tracks
 *
 * Adds/publishes tracks to a Cloudflare
 * media session.
 *
 * Body:
 *
 * {
 *   "sessionId": "...",
 *   "offerSdp": "v=0...",
 *   "tracks": [
 *     {
 *       "trackName": "phase1-video-...",
 *       "kind": "video",
 *       "direction": "publish",
 *       "mid": "0"
 *     },
 *     {
 *       "trackName": "phase1-audio-...",
 *       "kind": "audio",
 *       "direction": "publish",
 *       "mid": "1"
 *     }
 *   ]
 * }
 */
export async function testPublishTracks(
  req: Request,
  res: Response,
  next: NextFunction,
): Promise<void> {
  try {
    const sessionId =
      String(
        req.body?.sessionId ??
          "",
      ).trim();

    const offerSdp =
      typeof req.body?.offerSdp ===
      "string"
        ? req.body.offerSdp
        : "";

    /*
     * Validate session.
     */
    if (!sessionId) {
      res.status(400).json({
        status: "error",

        error: {
          code:
            "MEDIA_SESSION_ID_REQUIRED",

          message:
            "sessionId is required.",
        },
      });

      return;
    }

    /*
     * Validate SDP.
     */
    if (!offerSdp.trim()) {
      res.status(400).json({
        status: "error",

        error: {
          code:
            "MEDIA_SDP_OFFER_REQUIRED",

          message:
            "offerSdp is required.",
        },
      });

      return;
    }

    /*
     * Validate tracks.
     */
    const tracks =
      Array.isArray(
        req.body?.tracks,
      )
        ? req.body.tracks
        : [];

    if (
      tracks.length === 0
    ) {
      res.status(400).json({
        status: "error",

        error: {
          code:
            "MEDIA_TRACKS_REQUIRED",

          message:
            "At least one track is required.",
        },
      });

      return;
    }

    /*
     * Phase 1 diagnostics.
     *
     * This lets us verify that MID survives:
     *
     * Browser
     *   ↓
     * API
     *   ↓
     * Provider
     */
    console.log(
      "[media-test] Incoming tracks:",
      JSON.stringify(
        tracks,
        null,
        2,
      ),
    );

    console.log(
      "[media-test] Incoming SDP:",
      {
        length:
          offerSdp.length,

        ending:
          JSON.stringify(
            offerSdp.slice(-100),
          ),
      },
    );

    /*
     * Validate every track before
     * passing it to the provider.
     */
    for (
      let index = 0;
      index < tracks.length;
      index++
    ) {
      const track =
        tracks[index];

      if (
        !track ||
        typeof track !==
          "object"
      ) {
        res.status(400).json({
          status: "error",

          error: {
            code:
              "MEDIA_TRACK_INVALID",

            message:
              `Track at index ${index} is invalid.`,
          },
        });

        return;
      }

      const trackName =
        typeof track.trackName ===
        "string"
          ? track.trackName.trim()
          : "";

      if (!trackName) {
        res.status(400).json({
          status: "error",

          error: {
            code:
              "MEDIA_TRACK_NAME_REQUIRED",

            message:
              `Track at index ${index} requires trackName.`,
          },
        });

        return;
      }

      if (
        track.kind !==
          "audio" &&
        track.kind !==
          "video"
      ) {
        res.status(400).json({
          status: "error",

          error: {
            code:
              "MEDIA_TRACK_KIND_INVALID",

            message:
              `Track "${trackName}" must have kind "audio" or "video".`,
          },
        });

        return;
      }

      if (
        track.direction !==
        "publish"
      ) {
        res.status(400).json({
          status: "error",

          error: {
            code:
              "MEDIA_TRACK_DIRECTION_INVALID",

            message:
              `Track "${trackName}" must have direction "publish".`,
          },
        });

        return;
      }

      const mid =
        typeof track.mid ===
        "string"
          ? track.mid.trim()
          : "";

      if (!mid) {
        res.status(400).json({
          status: "error",

          error: {
            code:
              "MEDIA_TRACK_MID_REQUIRED",

            message:
              `Track "${trackName}" is missing WebRTC mid.`,
          },
        });

        return;
      }
    }

    console.log(
      "[media-test] Validated tracks:",
      tracks.map(
        (track: any) => ({
          trackName:
            track.trackName,

          kind:
            track.kind,

          direction:
            track.direction,

          mid:
            track.mid,
        }),
      ),
    );

    /*
     * Publish tracks through the
     * Cloudflare provider.
     */
    const result =
      await cloudflareRealtimeProvider.publishTracks({
        sessionId,

        offerSdp,

        tracks,
      });

    res.json({
      status: "ok",

      data: {
        answerSdp:
          result.answerSdp,

        offerSdp:
          result.offerSdp,

        tracks:
          result.tracks,

        requiresRenegotiation:
          result.requiresRenegotiation,
      },
    });
  } catch (error) {
    next(error);
  }
}