import {
  MEDIA_NEGOTIATION_STATES,
  MEDIA_PARTICIPANT_ROLES,
  MEDIA_ROOM_STATUSES,
  MEDIA_SESSION_STATUSES,
  MEDIA_TRACK_DIRECTIONS,
  MEDIA_TRACK_KINDS,
} from "./media.constants";

export type MediaParticipantRole =
  (typeof MEDIA_PARTICIPANT_ROLES)[number];

export type MediaSessionStatus =
  (typeof MEDIA_SESSION_STATUSES)[number];

export type RoomMediaStatus =
  (typeof MEDIA_ROOM_STATUSES)[number];

export type MediaTrackKind =
  (typeof MEDIA_TRACK_KINDS)[number];

export type MediaTrackDirection =
  (typeof MEDIA_TRACK_DIRECTIONS)[number];

export type MediaNegotiationState =
  (typeof MEDIA_NEGOTIATION_STATES)[number];

/* ============================================================
 * MEDIA SESSION
 * ========================================================== */

export interface MediaSession {
  sessionId: string;

  roomId: string;

  userId: string;

  role: MediaParticipantRole;

  generation: number;

  status: MediaSessionStatus;

  createdAt: number;

  lastHeartbeatAt: number;
}

/* ============================================================
 * MEDIA SESSION CREATION
 * ========================================================== */

export interface CreateMediaSessionInput {
  roomId: string;

  userId: string;

  role: MediaParticipantRole;

  generation: number;

  /**
   * SDP offer generated by the WebRTC client.
   *
   * This is optional at the type level because the
   * session itself can be created independently from
   * adding tracks. The actual Cloudflare media
   * negotiation happens through tracks/new.
   */
  offerSdp?: string;
}

export interface CreateMediaSessionResult {
  session: MediaSession;

  sessionDescription?: {
    type: "offer" | "answer";

    sdp: string;
  };
}

/* ============================================================
 * TRACKS
 * ========================================================== */

export interface MediaTrack {
  trackName: string;

  kind: MediaTrackKind;

  direction: MediaTrackDirection;

  
  mid?: string;
}
export interface RemoteMediaTrack {
  sessionId: string;

  trackName: string;
}

/* ============================================================
 * HOST
 * ========================================================== */

export interface HostMediaState {
  userId: string;

  sessionId: string;

  videoTrackName: string;

  audioTrackName: string;

  generation: number;

  status: MediaSessionStatus;

  connectedAt: number;

  lastHeartbeatAt: number;
}

/* ============================================================
 * SPEAKER
 * ========================================================== */

export interface SpeakerMediaState {
  userId: string;

  sessionId: string;

  audioTrackName: string;

  generation: number;

  status: MediaSessionStatus;

  joinedAt: number;

  lastHeartbeatAt: number;
}

/* ============================================================
 * VIEWER
 * ========================================================== */

export interface ViewerMediaState {
  userId: string;

  sessionId: string;

  generation: number;

  status: MediaSessionStatus;

  joinedAt: number;

  lastHeartbeatAt: number;

  lastSequence: number;
}

/* ============================================================
 * ROOM MEDIA STATE
 * ========================================================== */

export interface RoomMediaState {
  roomId: string;

  status: RoomMediaStatus;

  generation: number;

  sequence: number;

  host: HostMediaState | null;

  speakers: Record<
    string,
    SpeakerMediaState
  >;

  viewerCount: number;

  updatedAt: number;
}

/* ============================================================
 * PUBLISH TRACKS
 * ========================================================== */

export interface PublishTracksInput {
  sessionId: string;

  offerSdp: string;

  tracks: MediaTrack[];
}

/* ============================================================
 * SUBSCRIBE TRACKS
 * ========================================================== */

export interface SubscribeTracksInput {
  sessionId: string;

  offerSdp?: string;

  tracks: RemoteMediaTrack[];
}

/* ============================================================
 * RENEGOTIATION
 * ========================================================== */

export interface RenegotiateInput {
  sessionId: string;

  answerSdp: string;
}

/* ============================================================
 * CLOSE TRACKS
 * ========================================================== */

export interface CloseTracksInput {
  sessionId: string;

  trackNames: string[];
}

/* ============================================================
 * UPDATE TRACKS
 * ========================================================== */

export interface UpdateTracksInput {
  sessionId: string;

  tracks: MediaTrack[];
}

/* ============================================================
 * NEGOTIATION RESULT
 * ========================================================== */

export interface MediaNegotiationResult {
  answerSdp?: string;

  offerSdp?: string;

  tracks: MediaTrack[];

  requiresRenegotiation: boolean;
}

/* ============================================================
 * PROVIDER SESSION INFO
 * ========================================================== */

export interface MediaSessionInfo {
  sessionId: string;

  status: MediaSessionStatus | "unknown";

  createdAt?: number;

  metadata?: Record<
    string,
    unknown
  >;
}

/* ============================================================
 * NEGOTIATION STATE
 * ========================================================== */

export interface MediaNegotiation {
  id: string;

  sessionId: string;

  generation: number;

  state: MediaNegotiationState;

  createdAt: number;

  attempts: number;
}

/* ============================================================
 * IDEMPOTENCY
 * ========================================================== */

export type IdempotencyStatus =
  | "processing"
  | "completed"
  | "failed";

export interface IdempotencyRecord {
  key: string;

  operation: string;

  roomId: string;

  userId: string;

  status: IdempotencyStatus;

  response?: unknown;

  createdAt: number;

  expiresAt: number;
}

/* ============================================================
 * LEASE
 * ========================================================== */

export interface MediaLease {
  participantId: string;

  sessionId: string;

  role: MediaParticipantRole;

  generation: number;

  lastHeartbeatAt: number;

  expiresAt: number;
}

/* ============================================================
 * PROVIDER CONFIGURATION
 * ========================================================== */

export interface MediaProviderConfig {
  apiBase: string;

  appId: string;

  appSecret: string;
}